apiVersion: v1
kind: Pod
metadata:
  name: devops-demo
  labels:
    app: devops-demo
spec:
  containers:
    - name: devops-demo
      image: ghcr.io/sangram-7-cmd/python-app:latest
      ports:
        - containerPort: 5000